version: "3"
services:
  mongodb:
    image: sbk2k1/hm_mongo
    restart: always
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db

  node-backend:
    image: sbk2k1/hm_node
    expose:
      - ${PORT}
    ports:
      - 9876:${PORT}
    networks:
      - my-network
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGO_DB_URL=${MONGO_DB_URL}
    depends_on:
      - mongodb

  react-frontend:
    image: sbk2k1/hm_react
    ports:
      - 1234:3000
    expose:
      - 3000
    networks:
      - my-network
    environment:
      - REACT_APP_ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    depends_on:
      - node-backend

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
