version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db

  node-backend:
    build:
      context: ./node-backend
    depends_on:
      - mongodb
    expose:
      - ${PORT}
    ports:
      - 9876:${PORT}
    networks:
      - my-network
    volumes:
      - ./node-backend/config/mongodb-url.txt:/app/config/mongodb-url.txt:ro
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - MONGO_DB_URL=${MONGO_DB_URL}
      
  react-frontend:
    build:
      context: ./react-frontend
    depends_on:
      - node-backend
    ports:
      - 1234:3000
    expose:
      - 3000
    links:
      - node-backend
    networks:
      - my-network
    environment:
      - REACT_APP_ACCESS_TOKEN_SECRET=${REACT_APP_ACCESS_TOKEN_SECRET}

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
